# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'T-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for T-Demo
  pod 'JPVideoPlayer', '~> 3.2.0-beta'

  # AWS 相关
  pod 'Amplify'
  pod 'Amplify/Tools'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSDataStorePlugin'
  
  # FB 相关
  pod 'FBSDKLoginKit'
  
  pod 'YYWebImage', '~> 1.0.5'
  
  #ts 转 mp4
  pod "mobile-ffmpeg-full"
  pod 'SVProgressHUD', '~> 2.2.5'


  target 'T-DemoTests' do
    inherit! :search_paths
    # Pods for testing


  end

  target 'T-DemoUITests' do
    # Pods for testing
  end

end
